# -*- coding: utf-8 -*-
"""Sudi PlannerAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LhTUbwm6t-zk5bsgQ-YBDAO9tB2p0i7b

# Planner Agent

---
Refinements:
- Adjusted how many subtasks the agent should generate for strategic and financial
- Adjusted the suggested considerations/metrics to give for the subtasks
- Adjusted the task description to text to be more clear and straightforward
"""

# =============================================================================
# Setup (libraries, OpenAI key)
# =============================================================================

import json
import re
import os
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional
from openai import OpenAI
from google.colab import files

# Set your OpenAI API key in environment
os.environ["OPENAI_API_KEY"] = "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"

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# =============================================================================
# Planner Agent
# =============================================================================

class OpenAIPlannerAgent:
    def __init__(
        self,
        task_description: str,
        temperature: float = 0.0,
        max_tokens: int = 4000,
        cache_dir: str = "./planner_cache",
        use_cache: bool = True,
    ):
        self.task_description = task_description.strip()
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.use_cache = use_cache
        self.cache_dir = Path(cache_dir)
        self.cache_dir.mkdir(exist_ok=True, parents=True)

    # ----------------------------
    # Cache helpers
    # ----------------------------
    def _get_cache_key(self, suffix="") -> str:
        import hashlib
        content = f"{self.task_description}|{suffix}"
        return hashlib.md5(content.encode()).hexdigest()

    def _load_from_cache(self, suffix=""):
        if not self.use_cache:
            return None
        cache_file = self.cache_dir / f"{self._get_cache_key(suffix)}.json"
        if cache_file.exists():
            with open(cache_file, 'r') as f:
                return json.load(f)
        return None

    def _save_to_cache(self, result: dict, suffix=""):
        cache_file = self.cache_dir / f"{self._get_cache_key(suffix)}.json"
        with open(cache_file, 'w') as f:
            json.dump(result, f, indent=2)

    # ----------------------------
    # Build prompt for strategic or financial subtasks
    # ----------------------------
    def _build_subtask_prompt(self, subtask_type: str) -> str:
        if subtask_type == 'strategic':
            instructions = """
            Generate at least 7 strategic subtasks for the task below.
            Each subtask must include:
            id, title, objective, checklist, data_required, priority, complexity, justification.
            Return ONLY valid JSON.
            Suggested considerations:
            - Brand dilution risks
            - Operational integration challenges
            - Employee resistance/morale
            - Supply chain complexity
            - Customer experience implications
            - Competitive positioning changes
            - Resource allocation
            """
        elif subtask_type == 'financial':
            instructions = """
            Generate at least 10 financial subtasks for the task below.
            Each subtask must include:
            id, title, objective, metrics (name, formula, interpretation), checklist, data_required, priority, complexity, justification.
            Return ONLY valid JSON.
            Suggested metrics to consider:
            - Inventory Turnover
            - Cash Conversion Cycle
            - Gross Margin
            - Net Profit Margin
            - SG&A %
            - ROI
            - DIO / DSO / DPO
            - Operating Margin / EBIT Margin
            - ROA / ROE
            - Revenue per Employee
            - CAC / CLTV
            - Liquidity Ratios
            - Revenue Growth Rate
            - COGS %
            """
        else:
            raise ValueError("Invalid subtask_type")

        prompt = f"""
        TASK: {self.task_description}

        INSTRUCTIONS: {instructions}

        OUTPUT FORMAT:
        Return ONLY a JSON array of subtasks. For financial subtasks, include metrics.
        """
        return prompt

    # ----------------------------
    # Call OpenAI API
    # ----------------------------
    def _call_openai(self, prompt: str) -> str:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
            temperature=self.temperature,
            max_tokens=self.max_tokens
        )
        return response.choices[0].message.content

    # ----------------------------
    # Generate subtasks (strategic + financial)
    # ----------------------------
    def create_subtasks(self):
        output = {"strategic_subtasks": [], "financial_subtasks": []}

        # ----------------------------
        # Strategic subtasks
        # ----------------------------
        cached_strat = self._load_from_cache("strategic")
        if cached_strat:
            output["strategic_subtasks"] = cached_strat
        else:
            prompt_strat = self._build_subtask_prompt("strategic")
            response_strat = self._call_openai(prompt_strat)
            try:
                output["strategic_subtasks"] = json.loads(response_strat)
            except json.JSONDecodeError:
                print("⚠️ Strategic JSON parse failed. Returning empty list.")
                output["strategic_subtasks"] = []
            self._save_to_cache(output["strategic_subtasks"], "strategic")

        # ----------------------------
        # Financial subtasks
        # ----------------------------
        cached_fin = self._load_from_cache("financial")
        if cached_fin:
            output["financial_subtasks"] = cached_fin
        else:
            prompt_fin = self._build_subtask_prompt("financial")
            response_fin = self._call_openai(prompt_fin)
            try:
                output["financial_subtasks"] = json.loads(response_fin)
            except json.JSONDecodeError:
                print("⚠️ Financial JSON parse failed. Returning empty list.")
                output["financial_subtasks"] = []
            self._save_to_cache(output["financial_subtasks"], "financial")

        # ----------------------------
        # Metadata & summary
        # ----------------------------
        plan = {
            "metadata": {
                "task_description": self.task_description,
                "generated_at": datetime.now().isoformat(),
                "model": "gpt-3.5-turbo",
            },
            "subtasks": output,
            "summary": {
                "total_strategic": len(output["strategic_subtasks"]),
                "total_financial": len(output["financial_subtasks"])
            }
        }
        return plan

    # ----------------------------
    # Display summary
    # ----------------------------
    def display_summary(self, plan: dict):
        print("\n--- ANALYSIS PLAN SUMMARY ---")
        print(f"Strategic subtasks: {plan['summary']['total_strategic']}")
        print(f"Financial subtasks: {plan['summary']['total_financial']}")
        print("\nStrategic Subtasks:")
        for t in plan['subtasks']['strategic_subtasks']:
            print(f"• {t['title']}")
        print("\nFinancial Subtasks:")
        for t in plan['subtasks']['financial_subtasks']:
            print(f"• {t['title']}")

# =============================================================================
# Strategic Analyzer Function
# =============================================================================

def colab_example_openai():
    task = """
Should company ABC adopt XYZ's business model?

Context:
- ABC: Traditional brick-and-mortar retailer, low product variety, high inventory turnover
- XYZ: Online-first company, high product variety, longer cash conversion cycles

Analysis needed:
1. Strategic: brand dilution risks, operational integration challenges, employee impact, supply chain complexity, competitive positioning changes, customer experience implications
2. Financial: inventory turnover, profitability, SG&A, COGS, Operating / EBIT Margin, gross margin, cash conversion cycle, ROI, net profit margin, ROA & ROE, Liquidity Ratios, Revenue per Employee
3. Provide recommendation with justification
"""

    # Create agent instance
    planner = OpenAIPlannerAgent(
        task_description=task,
        max_tokens=4000  # increased for longer outputs
    )

    # Generate subtasks
    plan = planner.create_subtasks()

    # Display summary using built-in method
    planner.display_summary(plan)

    # Save JSON to file
    filename = "planner_output.json"
    with open(filename, "w") as f:
        json.dump(plan, f, indent=2)

    # Provide download link in Colab
    files.download(filename)

    return plan

# =============================================================================
# Run RAG Agent
# =============================================================================
plan = colab_example_openai()

"""# ABC vs XYZ Business Model Evaluation

---

# 📌 Strategic Subtasks

---

## 1. Assess Brand Dilution Risks
- **Objective:** Evaluate the potential impact on ABC's brand identity and reputation if XYZ's model is adopted.
- **Checklist:**
  - Conduct brand perception surveys  
  - Analyze customer feedback  
  - Assess brand equity metrics  
- **Data Required:** Brand perception data, customer feedback, brand equity metrics  
- **Priority:** High  
- **Complexity:** High  
- **Justification:** Maintaining a strong brand identity is crucial for customer loyalty and competitive advantage.

---

## 2. Evaluate Operational Integration Challenges
- **Objective:** Identify obstacles in integrating XYZ's online-first operations with ABC’s brick-and-mortar setup.
- **Checklist:**
  - Conduct operational gap analysis  
  - Assess IT infrastructure compatibility  
  - Evaluate training needs for employees  
- **Data Required:** Operational data, IT infrastructure details, training records  
- **Priority:** High  
- **Complexity:** High  
- **Justification:** Smooth integration is essential for seamless operations and customer service.

---

## 3. Analyze Employee Impact
- **Objective:** Assess how adoption may affect morale, roles, and satisfaction.
- **Checklist:**
  - Conduct employee surveys  
  - Analyze turnover rates  
  - Evaluate training and development needs  
- **Data Required:** Survey results, turnover rates, training records  
- **Priority:** Medium  
- **Complexity:** Medium  
- **Justification:** Employee engagement directly impacts productivity and success.

---

## 4. Assess Supply Chain Complexity
- **Objective:** Evaluate the effect of increased product variety and longer cash cycles.
- **Checklist:**
  - Analyze current supply chain processes  
  - Assess inventory management systems  
  - Evaluate supplier relationships  
- **Data Required:** Supply chain data, inventory systems, supplier contracts  
- **Priority:** High  
- **Complexity:** High  
- **Justification:** Efficient supply chains are critical for cost control and demand fulfillment.

---

## 5. Analyze Competitive Positioning Changes
- **Objective:** Determine how adoption impacts ABC’s competitive standing.
- **Checklist:**
  - Conduct competitor analysis  
  - Evaluate market trends  
  - Assess unique selling propositions  
- **Data Required:** Competitor data, market trends, USP comparisons  
- **Priority:** High  
- **Complexity:** High  
- **Justification:** Competitive positioning is essential for long-term growth.

---

## 6. Evaluate Customer Experience Implications
- **Objective:** Assess the impact on overall customer experience.
- **Checklist:**
  - Conduct customer feedback analysis  
  - Evaluate customer service processes  
  - Assess online user experience  
- **Data Required:** Feedback data, service records, UX metrics  
- **Priority:** High  
- **Complexity:** High  
- **Justification:** Customer experience directly affects loyalty, retention, and revenue.

---

## 7. Assess Resource Allocation Needs
- **Objective:** Determine financial, human, and technological resources required.
- **Checklist:**
  - Conduct resource gap analysis  
  - Evaluate budget allocation  
  - Assess technology upgrade needs  
- **Data Required:** Resource allocation data, budgets, technology requirements  
- **Priority:** High  
- **Complexity:** High  
- **Justification:** Proper resource allocation ensures successful implementation.

---

# 📊 Financial Subtasks

---

## 1. Inventory Turnover
- **Objective:** Assess how quickly inventory is sold.
- **Formula:** `COGS / Average Inventory`  
- **Interpretation:** Higher is better.
- **Data Required:** COGS, Average Inventory  
- **Priority:** High | **Complexity:** Medium  
- **Justification:** Measures operational efficiency.

---

## 2. Cash Conversion Cycle (CCC)
- **Formula:** `DIO + DSO - DPO`  
- **Interpretation:** Shorter cycle = better liquidity.
- **Data Required:** DIO, DSO, DPO  
- **Priority:** High | **Complexity:** High  
- **Justification:** Key working capital metric.

---

## 3. Gross Margin
- **Formula:** `(Revenue - COGS) / Revenue`  
- **Interpretation:** Higher = better pricing power.
- **Data Required:** Revenue, COGS  
- **Priority:** High | **Complexity:** Low  
- **Justification:** Core profitability metric.

---

## 4. Net Profit Margin
- **Formula:** `Net Profit / Revenue`  
- **Interpretation:** Measures bottom-line health.
- **Data Required:** Net Profit, Revenue  
- **Priority:** High | **Complexity:** Low  

---

## 5. SG&A %
- **Formula:** `(SG&A / Revenue) × 100`  
- **Interpretation:** Lower = better cost control.
- **Data Required:** SG&A, Revenue  
- **Priority:** Medium | **Complexity:** Medium  

---

## 6. Return on Investment (ROI)
- **Formula:** `(Net Profit / Total Investment) × 100`  
- **Interpretation:** Higher = better capital efficiency.
- **Data Required:** Net Profit, Total Investment  
- **Priority:** High | **Complexity:** Medium  

---

## 7. Operating Margin
- **Formula:** `Operating Income / Revenue`  
- **Interpretation:** Core business profitability.
- **Data Required:** Operating Income, Revenue  
- **Priority:** High | **Complexity:** Medium  

---

## 8. Return on Assets (ROA)
- **Formula:** `Net Income / Total Assets`  
- **Interpretation:** Asset utilization efficiency.
- **Data Required:** Net Income, Total Assets  
- **Priority:** High | **Complexity:** Medium  

---

## 9. Return on Equity (ROE)
- **Formula:** `Net Income / Shareholders' Equity`  
- **Interpretation:** Shareholder return metric.
- **Data Required:** Net Income, Shareholders’ Equity  
- **Priority:** High | **Complexity:** Medium  

---

## 10. Revenue per Employee
- **Formula:** `Revenue / Number of Employees`  
- **Interpretation:** Workforce productivity.
- **Data Required:** Revenue, Employee Count  
- **Priority:** Medium | **Complexity:** Low  

---

"""