# -*- coding: utf-8 -*-
"""Sudi StrategicAnalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNBT5yOs5S59ZUSC8TpMgOVKdvxFeDSq

# Strategic Analyzer RAG

---
Refinements:
- Adjusted business description for ABC and XYZ to give the most relevant information to the agent
- Made prompt as clear as possible through some iterations
"""

# ========================================
# Install Packages
# ========================================
!pip uninstall -y fitz
!pip install --upgrade pymupdf
!pip install -q tiktoken
!pip install -q openai
!pip install -q faiss-cpu

# =========================
# Imports & Config
# =========================
import os
import json
from pathlib import Path
import numpy as np
import faiss
import pandas as pd
import fitz  # PyMuPDF

try:
    import tiktoken
except ImportError:
    tiktoken = None

try:
    import openai
except ImportError:
    raise RuntimeError("Install openai: pip install openai")

# =========================
# Set up OpenAI key
# =========================
os.environ["OPENAI_API_KEY"] = "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"

# --------------------
# Configuration
# --------------------
openai.api_key = os.getenv("OPENAI_API_KEY")
BASE_PATH = "/content"
PLANNER_JSON_PATH = f"{BASE_PATH}/planner_output (1).json"
OUTPUT_RESULTS = f"{BASE_PATH}/strategic_results.json"
EMBED_MODEL = os.getenv("EMBED_MODEL", "text-embedding-3-small")
CHAT_MODEL = os.getenv("CHAT_MODEL", "gpt-3.5-turbo")

# --------------------
# Helper Functions
# --------------------
def load_pdf(filepath):
    doc = fitz.open(filepath)
    return "\n".join([page.get_text() for page in doc])

def load_txt(filepath):
    with open(filepath, "r") as f:
        return f.read()

def load_csv(filepath):
    df = pd.read_csv(filepath)
    return df.to_string()

def chunk_text(text, max_tokens=500, overlap=50):
    if tiktoken:
        encoder = tiktoken.get_encoding("cl100k_base")
        tokens = encoder.encode(text)
        chunks = []
        i = 0
        while i < len(tokens):
            chunk = encoder.decode(tokens[i:i+max_tokens])
            chunks.append(chunk)
            i += max_tokens - overlap
        return chunks
    else:
        # fallback: simple character-based
        chunks = []
        start = 0
        while start < len(text):
            end = start + max_tokens*4  # approx char -> token ratio
            chunks.append(text[start:end])
            start = end - overlap*4
        return chunks

def embed_texts(texts):
    embeddings = []
    for text in texts:
        resp = openai.embeddings.create(
            model=EMBED_MODEL,
            input=text
        )
        embeddings.append(resp.data[0].embedding)
    return np.array(embeddings).astype("float32")

def retrieve_context(query, chunks, index, k=4):
    query_vec = embed_texts([query])[0]
    query_vec = np.array([query_vec]).astype("float32")
    distances, indices = index.search(query_vec, k)
    return "\n".join([chunks[i] for i in indices[0]])

def run_chat(prompt):
    resp = openai.chat.completions.create(
        model=CHAT_MODEL,
        messages=[
            {"role": "system", "content": "You are a professional strategy consultant."},
            {"role": "user", "content": prompt}
        ]
    )
    return resp.choices[0].message.content

# =========================
# Load Planner Output
# =========================
with open(PLANNER_JSON_PATH, "r") as f:
    planner_data = json.load(f)

# Load strategic subtasks
strategic_subtasks = planner_data["subtasks"]["strategic_subtasks"]

# =========================
# Define Business Descriptions
# =========================
abc_description = """
ABC International Group is a global fashion and design company that has established itself as one of
the world's largest international clothing retailers, operating around 4,500 stores across 80 markets
with online sales in 65 countries. Founded in 1950 by Norwegian entrepreneur Erik Larsson, the company began as
a single women's clothing store called "Lydia" and has evolved into a diversified fashion empire generating
approximately $26.1 billion USD in annual revenue.
"""
xyz_description = """
XYZ Personalized Styling is a leading online personal styling service that transformed the
retail industry by combining advanced data analytics with human expertise to deliver personalized
clothing and accessories directly to customers’ homes. Founded in 2010 by Laura Benton and headquartered
in Portland, Oregon, the company pioneered a unique business model that ships curated “Style Packs”
containing clothing items tailored to individual preferences, sizes, and budgets.
"""
print("✅ Business descriptions defined!")
print(f"ABC: {len(abc_description)} characters")
print(f"XYZ: {len(xyz_description)} characters")

# =========================
# Load Research Documents
# =========================
all_text = abc_description + "\n" + xyz_description  # Include business descriptions first

for file in Path(BASE_PATH).iterdir():
    if file.suffix.lower() == ".pdf":
        all_text += "\n" + load_pdf(file)
    elif file.suffix.lower() == ".txt":
        all_text += "\n" + load_txt(file)
    elif file.suffix.lower() == ".csv":
        all_text += "\n" + load_csv(file)

# =========================
# Chunk Texts
# =========================
chunks = chunk_text(all_text)

# =========================
# Embed Chunks
# =========================
embeddings = embed_texts(chunks)

# =========================
# Build FAISS Index
# =========================
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

# =========================
# Run Subtasks Analysis
# =========================
results = {}
for task in strategic_subtasks:
    query = task.get("objective") or task.get("title")
    context = retrieve_context(query, chunks, index)
    full_prompt = f"Context:\n{context}\n\nQuestion:\n{query}\n\nProvide a clear, structured consulting-style answer."
    output = run_chat(full_prompt)
    results[task["id"]] = {
        "task": query,
        "analysis": output
    }

# =========================
# Save Results
# =========================
with open(OUTPUT_RESULTS, "w") as f:
    json.dump(results, f, indent=2)

print("✅ Strategic Analysis Completed & Saved")

"""# Strategic Subtasks Analysis

## 1. Evaluate the potential impact on ABC's brand identity and reputation if they adopt XYZ's business model

**Analysis:**  
To effectively evaluate the potential impact on ABC International Group's brand identity and reputation if they were to adopt XYZ Personalized Styling's business model, we need to consider various aspects:

1. **Brand Perception**  
   ABC has a strong reputation as a global fashion and design company. Adopting XYZ's personalized styling model could alter customer perception. While personalization can enhance loyalty, it must align with ABC's brand values to avoid confusion or distrust.

2. **Target Audience**  
   Understanding whether ABC's current customers value personalized styling is crucial. Alignment with XYZ's model can ensure a seamless transition; misalignment could reduce engagement and retention.

3. **Operational Feasibility**  
   ABC's large store and online network presents logistical challenges. Implementing personalized styling requires assessing scalability, cost, and integration within ABC’s infrastructure.

4. **Competitive Landscape**  
   Analyzing competitors and market trends helps understand if personalized styling strengthens ABC’s position or invites competitive pressure.

5. **Brand Communication and Marketing**  
   Clear communication and marketing strategies are needed to convey the value proposition and manage customer expectations.

6. **Risk Mitigation**  
   Conduct risk assessments, develop contingency plans, and monitor KPIs to minimize potential negative impacts on ABC's brand.

---

## 2. Identify potential obstacles in integrating XYZ's online-first operations with ABC's brick-and-mortar setup

**Analysis:**  
**Obstacles include:**

1. **Cultural Misalignment**  
   XYZ's online-first approach may clash with ABC’s traditional retail mindset.

2. **Technology Integration**  
   Integrating XYZ's analytics and online systems with ABC’s IT infrastructure is complex.

3. **Supply Chain Complexity**  
   Aligning online distribution with 4,500 physical stores requires robust logistics planning.

4. **Customer Experience Consistency**  
   Ensuring high service quality across online and offline channels is challenging.

5. **Staff Training and Engagement**  
   Employees need training to adapt to new roles and processes.

6. **Brand Integration and Messaging**  
   Harmonizing brand identity while integrating XYZ’s services is critical.

7. **Logistical Coordination**  
   Inventory tracking, order processing, and returns management must be synchronized.

---

## 3. Assess how adopting XYZ's business model may affect employee morale, job roles, and overall satisfaction

**Analysis:**  

1. **Change Management**  
   Employees may face challenges adapting to new processes; proper change management is essential.

2. **Job Roles and Responsibilities**  
   Traditional sales roles may evolve to include personalized styling; training and upskilling are required.

3. **Employee Morale**  
   Positive communication and clear expectations can boost morale; uncertainty may lower it.

4. **Employee Satisfaction**  
   Feedback mechanisms, recognition, and career development opportunities will enhance satisfaction.

---

## 4. Evaluate the impact of increased product variety and longer cash conversion cycles on ABC's supply chain

**Analysis:**  

1. **Increased Product Variety**  
   - **Benefits:** Broader customer appeal, increased sales, improved loyalty.  
   - **Challenges:** Complexity in sourcing, inventory, and distribution.  
   - **Supply Chain Implications:** Risk of stockouts, overstocking, obsolescence; requires agile supply chain management.

2. **Longer Cash Conversion Cycles**  
   - **Benefits:** Flexibility in managing working capital.  
   - **Challenges:** Strain on liquidity and financing costs.  
   - **Supply Chain Implications:** Efficiency in procurement, inventory, and sales processes is critical.

**Combined Effect:**  
Increased variety and longer cash cycles put pressure on inventory, cost control, and cash flow. Solutions include streamlined processes, supplier collaboration, advanced forecasting, and continuous performance monitoring.

---

## 5. Assess how adopting XYZ's business model may impact ABC's competitive position in the market

**Analysis:**  

1. **Strengths of ABC:**  
   - Global presence, diversified product portfolio, strong brand.

2. **Strengths of XYZ:**  
   - Innovative online-first model, personalization, efficient operations.

3. **Potential Impact:**  
   - Enhanced customer experience, increased engagement, competitive advantage.

4. **Challenges:**  
   - Operational integration, cultural alignment, market response from competitors.

---

## 6. Assess how adopting XYZ's business model may impact the overall customer experience at ABC

**Analysis:**  

1. **Understanding XYZ’s Model:**  
   Personalized Style Packs, data-driven recommendations, convenience, and engagement.

2. **Impact on ABC:**  
   - Enhanced personalization  
   - Improved engagement  
   - Greater convenience

3. **Operational Considerations:**  
   Investments in analytics, stylists, training, and integration with existing platforms.

4. **Measuring Success:**  
   KPIs for satisfaction, retention, and revenue; continuous feedback and improvement.

---

## 7. Determine the resources (financial, human, technological) required to successfully adopt XYZ's business model

**Analysis:**  

**Financial Resources:**  
- Technology investments (data analytics)  
- Inventory management system  
- Marketing and customer acquisition

**Human Resources:**  
- Data analysts and algorithm experts  
- Stylists and fashion experts  
- Customer support team

**Technological Resources:**  
- AI personalization tools  
- Enhanced e-commerce platform  
- Supply chain optimization tools


"""