# -*- coding: utf-8 -*-
"""Sudi SynthesizerAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ptxnZKQUp594O-ITvVJV-QqilxGl7R83

# Synthesizer Agent
---
Refinements:
- Adjusted instructions to agent to get the most-detailed and most relevant analysis and recommendation
- Adjusted the instructions for the recommendation structure to be as comprehensive as possible
"""

!pip install -q openai

# =============================================================================
# Import Libraries
# =============================================================================
import os
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, Any
from getpass import getpass

from openai import OpenAI

# =============================================================================
# Set up OpenAI key
# =============================================================================
os.environ["OPENAI_API_KEY"] = "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"

# =============================================================================
# Upload Analysis Results
# =============================================================================
from google.colab import files

print("="*80)
print("📁 UPLOAD YOUR ANALYSIS RESULTS")
print("="*80)

# Upload strategic analysis
print("\n1️⃣ Upload Strategic Analysis JSON:")
print("(e.g., strategic_analysis_report.json)")
strategic_upload = files.upload()

if not strategic_upload:
    print("❌ No strategic analysis uploaded!")
else:
    strategic_json_path = list(strategic_upload.keys())[0]
    print(f"✅ Uploaded: {strategic_json_path}")

# Upload financial analysis
print("\n2️⃣ Upload Financial/Quantitative Analysis JSON:")
print("(e.g., financial_analysis_report.json)")
financial_upload = files.upload()

if not financial_upload:
    print("❌ No financial analysis uploaded!")
else:
    financial_json_path = list(financial_upload.keys())[0]
    print(f"✅ Uploaded: {financial_json_path}")

# =============================================================================
# Configure Company Names
# =============================================================================
print("\n🏢 CONFIGURE COMPANY NAMES")
print("="*60)

# You can change these to match your assignment
COMPANY_A = "ABC"  # First company
COMPANY_B = "XYZ"  # Second company

print(f"Company A: {COMPANY_A}")
print(f"Company B: {COMPANY_B}")
print(f"\nQuestion: Should {COMPANY_A} adopt {COMPANY_B}'s business model?")

# =============================================================================
# Synthesizer Agent Class
# =============================================================================
class SynthesizerAgent:
    """Synthesizer Agent for final recommendation."""

    def __init__(self, openai_api_key: str = None):
        self.api_key = openai_api_key or os.getenv("OPENAI_API_KEY")
        self.client = OpenAI(api_key=self.api_key)

    def load_analysis_results(self, strategic_path: str, financial_path: str):
        """Load both analysis results."""
        print("📂 Loading analysis results...")

        with open(strategic_path, 'r') as f:
            strategic_data = json.load(f)
        print(f"✅ Loaded strategic analysis")

        with open(financial_path, 'r') as f:
            financial_data = json.load(f)
        print(f"✅ Loaded financial analysis")

        return {"strategic": strategic_data, "financial": financial_data}

    def extract_strategic_insights(self, strategic_data: Dict) -> str:
        """Extract strategic insights."""
        insights = []

        if "detailed_analyses" in strategic_data:
            for analysis in strategic_data["detailed_analyses"]:
                if "error" not in analysis:
                    insights.append(f"""
Subtask: {analysis.get('subtask_title', 'N/A')}
Priority: {analysis.get('priority', 'N/A')} | Confidence: {analysis.get('confidence', 'N/A')}

{analysis.get('analysis', 'No analysis')}
---
""")

        if "key_insights" in strategic_data:
            insights.append("\n=== KEY INSIGHTS ===\n")
            for insight in strategic_data["key_insights"]:
                insights.append(f"• {insight}\n")

        return "\n".join(insights) if insights else "No strategic insights."

    def extract_financial_insights(self, financial_data: Dict) -> str:
        """Extract financial insights."""
        insights = []

        if "detailed_analyses" in financial_data:
            for analysis in financial_data["detailed_analyses"]:
                if "error" not in analysis:
                    metrics = ', '.join(analysis.get('metrics_analyzed', []))
                    insights.append(f"""
Subtask: {analysis.get('subtask_title', 'N/A')}
Metrics: {metrics}
Priority: {analysis.get('priority', 'N/A')} | Confidence: {analysis.get('confidence', 'N/A')}

{analysis.get('analysis', 'No analysis')}
---
""")

        if "key_findings" in financial_data:
            insights.append("\n=== KEY FINDINGS ===\n")
            for finding in financial_data["key_findings"]:
                insights.append(f"• {finding}\n")

        return "\n".join(insights) if insights else "No financial insights."

    def create_synthesis_prompt(self, strategic_insights: str,
                               financial_insights: str,
                               company_a: str, company_b: str) -> str:
        """Create synthesis prompt."""

        return f"""
              You are a Senior Business Consultant making a FINAL RECOMMENDATION on whether {company_a} should adopt {company_b}'s business model.

              STRATEGIC ANALYSIS (QUALITATIVE):
              {strategic_insights}

              FINANCIAL ANALYSIS (QUANTITATIVE):
              {financial_insights}

              Provide a comprehensive recommendation with this structure with as muchd detail as possible:

              1. EXECUTIVE SUMMARY
                - Clear recommendation: Should {company_a} adopt {company_b}'s model? (Yes/No/Partial)
                - Confidence level (High/Medium/Low)
                - Top 3 reasons

              2. STRATEGIC CONSIDERATIONS
                - Key strategic factors
                - Strategic risks and opportunities
                - Weight: Strongly Favors / Favors / Neutral / Against / Strongly Against

              3. FINANCIAL CONSIDERATIONS
                - Key financial metrics and trends
                - Financial risks and opportunities
                - Weight: Strongly Favors / Favors / Neutral / Against / Strongly Against

              4. INTEGRATED ANALYSIS
                - How strategic and financial factors align or conflict
                - Most critical factors
                - Key trade-offs
                - Deal-breakers (if any)

              5. FINAL RECOMMENDATION
                - Clear decision: {company_a} SHOULD / SHOULD NOT / SHOULD PARTIALLY adopt {company_b}'s model
                - Justifications (ranked by importance):
                  i. [Most important]
                  ii. [Second most important]
                  iii. [Third most important]
                  iv. [Additional reasons]

              6. CONDITIONS & IMPLEMENTATION
                - If adopting, what conditions must be met?
                - Critical success factors
                - Risks to manage
                - Timeline/approach

              7. ALTERNATIVES
                - Hybrid approaches
                - Phased implementation options

              Be decisive, use specific evidence, cite metrics and findings, be balanced but clear.

              YOUR SYNTHESIS (1500-2000 words):
              """

    def generate_synthesis(self, strategic_path: str, financial_path: str,
                          company_a: str, company_b: str,
                          model: str = "gpt-4o-mini") -> Dict:
        """Generate complete synthesis."""

        print("\n" + "="*80)
        print("🔄 GENERATING SYNTHESIS")
        print("="*80)

        # Load data
        analysis_data = self.load_analysis_results(strategic_path, financial_path)

        # Extract insights
        print("\n🔍 Extracting insights...")
        strategic_insights = self.extract_strategic_insights(analysis_data["strategic"])
        financial_insights = self.extract_financial_insights(analysis_data["financial"])

        print(f"✅ Strategic insights: {len(strategic_insights)} chars")
        print(f"✅ Financial insights: {len(financial_insights)} chars")

        # Create prompt
        print(f"\n🤖 Generating synthesis with {model}...")
        print("⏳ This may take 30-60 seconds...")

        prompt = self.create_synthesis_prompt(
            strategic_insights, financial_insights, company_a, company_b)

        # Call LLM
        response = self.client.chat.completions.create(
            model=model,
            messages=[
                {
                    "role": "system",
                    "content": "You are a senior business consultant providing executive strategic recommendations."
                },
                {"role": "user", "content": prompt}
            ],
            temperature=0.3,
            max_tokens=4000)

        synthesis_text = response.choices[0].message.content

        print("✅ Synthesis complete!")

        # Compile results
        result = {
            "metadata": {
                "generated_at": datetime.now().isoformat(),
                "model": model,
                "companies": [company_a, company_b]
            },
            "full_synthesis": synthesis_text,
            "token_usage": {
                "total": response.usage.total_tokens,
                "prompt": response.usage.prompt_tokens,
                "completion": response.usage.completion_tokens
            }
        }

        return result

    def save_synthesis(self, result: Dict, json_path: str, md_path: str):
        """Save synthesis to files."""

        # Save JSON
        with open(json_path, 'w') as f:
            json.dump(result, f, indent=2)
        print(f"💾 Saved JSON: {json_path}")

        # Save Markdown
        markdown = f"""# Final Business Recommendation
                  ## {result['metadata']['companies'][0]} vs {result['metadata']['companies'][1]}

                  **Generated:** {result['metadata']['generated_at']}
                  **Model:** {result['metadata']['model']}

                  ---

                  {result['full_synthesis']}

                  ---

                  **Token Usage:** {result['token_usage']['total']} tokens
                  """

        with open(md_path, 'w') as f:
            f.write(markdown)
        print(f"📄 Saved Markdown: {md_path}")

print("✅ Synthesizer Agent class loaded!")

# =============================================================================
# Preview Analysis Files
# =============================================================================
def preview_analysis_files():
    """Preview what data we have from the analyses."""

    print("\n" + "="*80)
    print("👀 PREVIEW OF ANALYSIS FILES")
    print("="*80)

    # Strategic preview
    print("\n📊 STRATEGIC ANALYSIS:")
    print("-" * 60)
    try:
        with open(strategic_json_path, 'r') as f:
            strategic_data = json.load(f)

        if "summary_statistics" in strategic_data:
            stats = strategic_data["summary_statistics"]
            print(f"Total subtasks: {stats.get('total_subtasks_analyzed', 'N/A')}")
            print(f"Successful: {stats.get('successful_analyses', 'N/A')}")
            print(f"High confidence: {stats.get('high_confidence_analyses', 'N/A')}")

        if "detailed_analyses" in strategic_data:
            print(f"\nDetailed analyses available: {len(strategic_data['detailed_analyses'])}")
            for i, analysis in enumerate(strategic_data['detailed_analyses'][:3], 1):
                print(f"  {i}. {analysis.get('subtask_title', 'N/A')}")

    except Exception as e:
        print(f"❌ Error loading strategic: {e}")

    # Financial preview
    print("\n💰 FINANCIAL ANALYSIS:")
    print("-" * 60)
    try:
        with open(financial_json_path, 'r') as f:
            financial_data = json.load(f)

        if "summary_statistics" in financial_data:
            stats = financial_data["summary_statistics"]
            print(f"Total subtasks: {stats.get('total_subtasks_analyzed', 'N/A')}")
            print(f"Successful: {stats.get('successful_analyses', 'N/A')}")
            print(f"Unique metrics: {stats.get('unique_metrics_calculated', 'N/A')}")

        if "detailed_analyses" in financial_data:
            print(f"\nDetailed analyses available: {len(financial_data['detailed_analyses'])}")
            for i, analysis in enumerate(financial_data['detailed_analyses'][:3], 1):
                metrics = ', '.join(analysis.get('metrics_analyzed', []))
                print(f"  {i}. {analysis.get('subtask_title', 'N/A')} ({metrics})")

    except Exception as e:
        print(f"❌ Error loading financial: {e}")

# Run preview
preview_analysis_files()

# =============================================================================
# Generate Synthesis
# =============================================================================
print("\n" + "="*80)
print("🎯 GENERATING FINAL SYNTHESIS & RECOMMENDATION")
print("="*80)

# Initialize synthesizer
synthesizer = SynthesizerAgent()

# Generate synthesis
synthesis_result = synthesizer.generate_synthesis(
    strategic_path=strategic_json_path,
    financial_path=financial_json_path,
    company_a=COMPANY_A,
    company_b=COMPANY_B,
    model="gpt-3.5-turbo"
)

# Save results
output_json = "synthesis_final_recommendation.json"
output_md = "synthesis_final_recommendation.md"

synthesizer.save_synthesis(synthesis_result, output_json, output_md)

print("\n" + "="*80)
print("✅ SYNTHESIS COMPLETE!")
print("="*80)

# =============================================================================
# Display Results
# =============================================================================
print("\n" + "="*80)
print("📊 FINAL RECOMMENDATION")
print("="*80)

print(f"\n🏢 Companies: {COMPANY_A} vs {COMPANY_B}")
print(f"📅 Generated: {synthesis_result['metadata']['generated_at']}")
print(f"🤖 Model: {synthesis_result['metadata']['model']}")
print(f"🎫 Tokens used: {synthesis_result['token_usage']['total']}")

print("\n" + "="*80)
print("SYNTHESIS & RECOMMENDATION")
print("="*80)
print()
print(synthesis_result['full_synthesis'])

# =============================================================================
# Download Results
# =============================================================================
print("\n" + "="*80)
print("📥 DOWNLOAD RESULTS")
print("="*80)

from google.colab import files as colab_files

print("Downloading files...")

# Download JSON
colab_files.download(output_json)
print(f"✅ Downloaded: {output_json}")

# Download Markdown
colab_files.download(output_md)
print(f"✅ Downloaded: {output_md}")

print("\n" + "="*80)
print("🎉 ALL DONE!")
print("="*80)
print("""
You now have:
✓ synthesis_final_recommendation.json (full data)
✓ synthesis_final_recommendation.md (readable report)

The synthesis includes:
• Executive summary with clear recommendation
• Strategic considerations
• Financial considerations
• Integrated analysis
• Final recommendation with ranked justifications
• Implementation conditions
• Alternative approaches
""")

"""# Executive Summary

**Clear recommendation:** ABC should partially adopt XYZ's business model  
**Confidence level:** Medium  

**Top 3 reasons:**  
1. XYZ's model has shown success in increasing market share and customer engagement.  
2. ABC can leverage XYZ's innovative technology solutions to enhance its own operations.  
3. Partial adoption allows ABC to maintain its core strengths while benefiting from XYZ's best practices.

---

# Strategic Considerations

**Key strategic factors:**  
- Market positioning  
- Customer acquisition and retention  
- Innovation capabilities  

**Strategic risks and opportunities:**  
- **Risks:** Potential brand dilution, cultural integration challenges  
- **Opportunities:** Enhanced market competitiveness, access to new customer segments  

**Weight:** Favors

---

# Financial Considerations

**Key financial metrics and trends:**  
- Revenue growth  
- Profit margins  
- Return on investment  

**Financial risks and opportunities:**  
- **Risks:** Initial investment costs, uncertain ROI  
- **Opportunities:** Cost efficiencies, revenue diversification  

**Weight:** Neutral

---

# Integrated Analysis

**How strategic and financial factors align or conflict:**  
- Strategic factors favor adoption for market positioning and innovation, while financial factors are neutral due to uncertain ROI.  
- Most critical factors: Market positioning and innovation capabilities.  
- Key trade-offs: Initial investment costs vs. long-term growth potential.  
- Deal-breakers: Lack of cultural alignment and significant financial risks.

---

# Final Recommendation

**Clear decision:** ABC should partially adopt XYZ's model  

**Justifications:**  
1. Leveraging XYZ's technology for innovation.  
2. Enhancing market competitiveness through partial adoption.  
3. Mitigating risks of brand dilution through a phased approach.  
4. Maintaining core strengths while benefiting from best practices.

---

# Conditions & Implementation

**If adopting, what conditions must be met:**  
- Cultural integration plan  
- Clear ROI targets  
- Technology transfer agreements  

**Critical success factors:**  
- Strong leadership support  
- Effective change management  
- Continuous monitoring and evaluation  

**Risks to manage:**  
- Brand perception  
- Employee resistance  
- Integration challenges  

**Timeline/approach:**  
- Phased implementation over 12-18 months

---

# Alternatives

**Hybrid approaches:**  
- Selective adoption of specific aspects of XYZ's model  
- Joint ventures for technology collaboration  

**Phased implementation options:**  
- Pilot testing in key markets  
- Gradual rollout across business units

---

**Conclusion:**  
The recommendation for ABC to partially adopt XYZ's business model is based on a balanced assessment of strategic and financial factors. By leveraging XYZ's strengths while maintaining its own core competencies, ABC can position itself for sustainable growth and innovation in the competitive market landscape. The phased approach allows for risk mitigation and ensures a smoother integration process. With the right conditions in place and a clear implementation strategy, ABC can successfully navigate the transition and realize the benefits of adopting XYZ's model.

# Analysis of Results
- To save on costs, the agents were built using gpt-3.5-turbo. Using a more recent version of GPT may produce more nuanced, detailed, or better results.
"""